version: '3.2'

networks:
  phalcon-network:
    driver: bridge
services:
  phalcon-db:
    image: postgres:10.8-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    networks:
      - phalcon-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: phalcon
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c log_statement=all
  phalcon-web:
    build:
      context: .
      args:
        - env=driver
        - phalcon_version=v3.4.3
    ports:
      - 81:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    networks:
      - phalcon-network
    working_dir: /var/www/html
    depends_on:
      - phalcon-db